"""Added mood tracking to User model

Revision ID: 585ec0a29c5e
Revises: bd08e480a68b
Create Date: 2024-02-21 15:54:18.174530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585ec0a29c5e'
down_revision = 'bd08e480a68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mood_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mood_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mood_public')
        batch_op.drop_column('mood_timestamp')
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
